name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install bats
      run: |
        brew tap bats-core/bats-core
        brew install bats-core
    
    - name: Run tests
      run: |
        chmod +x ./fav
        bats test/*.bats
    
    - name: Shellcheck
      run: |
        brew install shellcheck
        shellcheck fav
        shellcheck fav-completion.bash